// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 15.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace P0TestCase
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.WinControls;
    using Microsoft.VisualStudio.TestTools.UITesting.WpfControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;


    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public partial class UIMap
    {

        /// <summary>
        /// RecordedMethod1 - Use 'RecordedMethod1Params' to pass parameters into this method.
        /// </summary>
        public void RecordedMethod1()
        {
            #region Variable Declarations
            WpfEdit uI_SearchfortemplatesAEdit = this.UIMicrosoftVisualStudiWindow.UIUserControl_1Custom.UISearchControlGroup.UI_SearchfortemplatesAEdit;
            WinClient uIDesktop1Client = this.UIItemWindow.UIItemWindow1.UIDesktop1Client;
            WpfText uIConfigureyournewprojText = this.UIMicrosoftVisualStudiWindow.UINpdDialogCustom.UIUserControl_1Custom.UIConfigureyournewprojText;
            WpfEdit uIProjectnameEdit = this.UIMicrosoftVisualStudiWindow.UINpdDialogCustom.UIUserControl_1Custom.UIScrollViewer_1Pane.UIProjectnameEdit;
            WpfEdit uILocationEdit = this.UIMicrosoftVisualStudiWindow.UINpdDialogCustom.UIUserControl_1Custom.UILocationCustom.UILocationEdit;
            #endregion

            // Type 'scope' in '_Search for templates (Alt+S)' text box
            uI_SearchfortemplatesAEdit.Text = this.RecordedMethod1Params.UI_SearchfortemplatesAEditText;

            // Type '{Enter}' in '_Search for templates (Alt+S)' text box
            Keyboard.SendKeys(uI_SearchfortemplatesAEdit, this.RecordedMethod1Params.UI_SearchfortemplatesAEditSendKeys, ModifierKeys.None);

            // Click 'Desktop 1' client
            Mouse.Click(uIDesktop1Client, new Point(8, 128));

            // Move 'Desktop 1' client to 'Configure your new project' label
            uIConfigureyournewprojText.EnsureClickable(new Point(1268, 49));
            Mouse.StartDragging(uIDesktop1Client, new Point(8, 128));
            Mouse.StopDragging(uIConfigureyournewprojText, new Point(1268, 49));

            // Type 'test' in 'Project name' text box
            uIProjectnameEdit.Text = this.RecordedMethod1Params.UIProjectnameEditText;

            // Type 'e:\test' in 'Location' text box
            uILocationEdit.Text = this.RecordedMethod1Params.UILocationEditText;
        }

        /// <summary>
        /// RecordedMethod2 - Use 'RecordedMethod2Params' to pass parameters into this method.
        /// </summary>
        public void RecordedMethod2()
        {
            #region Variable Declarations
            WpfEdit uI_SearchfortemplatesAEdit = this.UIMicrosoftVisualStudiWindow.UIUserControl_1Custom.UISearchControlGroup.UI_SearchfortemplatesAEdit;
            #endregion

            // Type 'scope' in '_Search for templates (Alt+S)' text box
            uI_SearchfortemplatesAEdit.Text = this.RecordedMethod2Params.UI_SearchfortemplatesAEditText;

            // Type '{Enter}' in '_Search for templates (Alt+S)' text box
            Keyboard.SendKeys(uI_SearchfortemplatesAEdit, this.RecordedMethod2Params.UI_SearchfortemplatesAEditSendKeys, ModifierKeys.None);
        }

        /// <summary>
        /// RecordedMethod3
        /// </summary>
        public void RecordedMethod3()
        {
            #region Variable Declarations
            WpfButton uICreatea_newprojectButton = this.UIMicrosoftVisualStudiWindow.UIUserControl_1Custom1.UIScrollViewer_1Pane.UICreatea_newprojectButton;
            #endregion

            // Click 'Create a _new project' button
            Mouse.Click(uICreatea_newprojectButton, new Point(193, 49));
        }

        /// <summary>
        /// RecordedMethod4 - Use 'RecordedMethod4Params' to pass parameters into this method.
        /// </summary>
        public void RecordedMethod4()
        {

            // Press keyboard shortcut keys '{LWin}'
            Keyboard.SendKeys(this.RecordedMethod4Params.SendKeys, ModifierKeys.None);

            // To test Windows Store apps, use the Coded UI Test project template for Windows Store apps under the Windows Store node.

            // To test Windows Store apps, use the Coded UI Test project template for Windows Store apps under the Windows Store node.

            // To test Windows Store apps, use the Coded UI Test project template for Windows Store apps under the Windows Store node.

            // To test Windows Store apps, use the Coded UI Test project template for Windows Store apps under the Windows Store node.

            // To test Windows Store apps, use the Coded UI Test project template for Windows Store apps under the Windows Store node.

            // To test Windows Store apps, use the Coded UI Test project template for Windows Store apps under the Windows Store node.
        }

        /// <summary>
        /// RecordedMethod5 - Use 'RecordedMethod5Params' to pass parameters into this method.
        /// </summary>
        public void RecordedMethod5()
        {
            #region Variable Declarations
            WinWindow uISnipperSnipasteWindow1 = this.UISnipperSnipasteWindow.UISnipperSnipasteWindow1;
            WinComboBox uIFilenameComboBox = this.UISaveimageasWindow.UIDetailsPanePane.UIFilenameComboBox;
            WinButton uISaveButton = this.UISaveimageasWindow.UISaveWindow.UISaveButton;
            #endregion

            // Type 'Control + s' in 'Snipper - Snipaste' window
            Keyboard.SendKeys(uISnipperSnipasteWindow1, this.RecordedMethod5Params.UISnipperSnipasteWindow1SendKeys, ModifierKeys.Control);

            // Select '22.png' in 'File name:' combo box
            uIFilenameComboBox.EditableItem = this.RecordedMethod5Params.UIFilenameComboBoxEditableItem;

            // Click '&Save' button
            Mouse.Click(uISaveButton, new Point(51, 24));
        }

        /// <summary>
        /// RecordedMethod6
        /// </summary>
        public void RecordedMethod6()
        {
            #region Variable Declarations
            WpfButton uIM0595948483737262615Button = this.UITest1637916794MicrosWindow.UIUserControl_1Custom.UILeftTabControlTabList.UISystemWindowsControlTabPage.UIM0595948483737262615Button;
            WinButton uIContexthelpButton = this.UIOptionsWindow.UIOptionsTitleBar.UIContexthelpButton;
            #endregion

            // Click 'M0,5 9,5 9,4 8,4 8,3 7,3 7,2 6,2 6,1 5,1 5,0 4,0 4...' button
            Mouse.Click(uIM0595948483737262615Button, new Point(48, 15));

            // Click 'Context help' button
            Mouse.Click(uIContexthelpButton, new Point(40, 1));
        }

        /// <summary>
        /// RecordedMethod7
        /// </summary>
        public void RecordedMethod7()
        {
            #region Variable Declarations
            WpfComboBox uIItemComboBox = this.UITest1638153053MicrosWindow.UIWpfTextViewHostCustom.UIUserControl_1Custom.UIAnalyticresourceText.UIItemComboBox;
            WpfEdit uISearchSolutionExplorEdit = this.UITest1638153053MicrosWindow.UITabGroupST003ae79031TabList.UISearchControlGroup.UISearchSolutionExplorEdit;
            WpfText uILocalMetadataRootText = this.UIOptionsWindow.UIItemWindow.UIItemClient.UIItemPane.UIItemCustom.UIScrollViewer_1Pane.UILocalMetadataRootText;
            #endregion

            // Click first combo box next to 'Analytic resource:' label
            Mouse.Click(uIItemComboBox, new Point(224, 23));

            // Click 'Search Solution Explorer (Ctrl+;)' text box
            Mouse.Click(uISearchSolutionExplorEdit, new Point(112, 5));

            // Click 'Local Metadata Root' label
            Mouse.Click(uILocalMetadataRootText, new Point(496, 30));

            // Double-Click 'Local Metadata Root' label
            Mouse.DoubleClick(uILocalMetadataRootText, new Point(496, 30));

            // Click 'Local Metadata Root' label
            Mouse.Click(uILocalMetadataRootText, new Point(496, 30));
        }

        /// <summary>
        /// RecordedMethod8
        /// </summary>
        public void RecordedMethod8()
        {
            #region Variable Declarations
            WinCheckBox uIPreviewpaneCheckBox = this.UIOpenProjectSolutionWindow.UICommandModuleToolBar.UIPreviewpaneCheckBox;
            WinWindow uISearchEditBoxWindow = this.UIOpenProjectSolutionWindow.UIItemWindow.UIOpenProjectSolutionClient.UISearchEditBoxWindow;
            WinEdit uISearchEditBoxEdit = this.UIOpenProjectSolutionWindow.UIItemWindow.UIOpenProjectSolutionClient.UISearchEditBoxEdit;
            #endregion

            // Click 'Preview pane' check box
            Mouse.Click(uIPreviewpaneCheckBox, new Point(6, 9));

            // Click 'SearchEditBox' window
            Mouse.Click(uISearchEditBoxWindow, new Point(215, 55));

            // Click 'SearchEditBox' text box
            Mouse.Click(uISearchEditBoxEdit, new Point(220, 27));
        }

        /// <summary>
        /// RecordedMethod9
        /// </summary>
        public void RecordedMethod9()
        {
            #region Variable Declarations
            WinSplitButton uIViewsSplitButton = this.UIOpenProjectSolutionWindow.UICommandModuleToolBar.UIViewsSplitButton;
            #endregion

            // Double-Click 'Views' split button
            Mouse.DoubleClick(uIViewsSplitButton, new Point(70, 13));
        }

        /// <summary>
        /// RecordedMethod10
        /// </summary>
        public void RecordedMethod10()
        {
            //#region Variable Declarations
            //WpfTreeItem uIScopescriptTreeItem = this.UISample_1MicrosoftVisWindow.UITabGroupST003ae79031TabList.UISolutionExplorerTabPage.UIScopescriptTreeItem;
            //WpfMenuItem uIBuildScriptMenuItem = this.UIWpfWindow.UIItemMenu.UIBuildScriptMenuItem;
            //#endregion

            //// Right-Click 'Scope.script' tree item
            //Mouse.Click(uIScopescriptTreeItem, MouseButtons.Right, ModifierKeys.None, new Point(148, 17));

            //// Click 'Build Script' menu item
            //Mouse.Click(uIBuildScriptMenuItem, new Point(87, 16));
        }

        /// <summary>
        /// RecordedMethod11
        /// </summary>
        //public void RecordedMethod11()
        //{
        //    #region Variable Declarations
        //    WinList uIDesktopList = this.UIProgramManagerWindow.UIFolderViewWindow.UIDesktopList;
        //    #endregion

        //    // Right-Click 'Desktop' list box
        //    Mouse.Click(uIDesktopList, MouseButtons.Right, ModifierKeys.None, new Point(1256, 329));

        //    // Click 'Desktop' list box
        //    Mouse.Click(uIDesktopList, new Point(1202, 480));
        //}

        ///// <summary>
        ///// RecordedMethod12
        ///// </summary>
        //public void RecordedMethod12()
        //{
        //    #region Variable Declarations
        //    WinList uIDesktopList = this.UIProgramManagerWindow.UIFolderViewWindow.UIDesktopList;
        //    #endregion

        //    // Click 'Desktop' list box
        //    Mouse.Click(uIDesktopList, new Point(1250, 449));

        //    // Right-Click 'Desktop' list box
        //    Mouse.Click(uIDesktopList, MouseButtons.Right, ModifierKeys.None, new Point(1232, 330));

        //    // Click 'Desktop' list box
        //    Mouse.Click(uIDesktopList, new Point(1237, 483));
        //}

        /// <summary>
        /// RecordedMethod13
        /// </summary>
        public void RecordedMethod13()
        {
            //#region Variable Declarations
            //WpfTreeItem uIScopescriptTreeItem = this.UISample_1MicrosoftVisWindow.UITabGroupST003ae79031TabList.UISolutionExplorerTabPage.UIScopescriptTreeItem;
            //WpfMenuItem uIDebugLocallyMenuItem = this.UIWpfWindow.UIItemMenu.UIDebugLocallyMenuItem;
            //#endregion

            //// Right-Click 'Scope.script' tree item
            //Mouse.Click(uIScopescriptTreeItem, MouseButtons.Right, ModifierKeys.None, new Point(105, 16));

            //// Click 'Debug Locally' menu item
            //Mouse.Click(uIDebugLocallyMenuItem, new Point(145, 21));
        }

        /// <summary>
        /// RecordedMethod14
        /// </summary>
        public void RecordedMethod14()
        {
            //#region Variable Declarations
            //WpfTreeItem uISample_1UnitTestTreeItem = this.UISample_1MicrosoftVisWindow.UITabGroupST003ae79031TabList.UISolutionExplorerTabPage.UISample_1UnitTestTreeItem;
            //WpfMenuItem uIRunTestsMenuItem = this.UIWpfWindow.UIProjectMenu.UIRunTestsMenuItem;
            //#endregion

            //// Right-Click 'Sample_1UnitTest' tree item
            //Mouse.Click(uISample_1UnitTestTreeItem, MouseButtons.Right, ModifierKeys.None, new Point(118, 18));

            //// Click 'Run Tests' menu item
            //Mouse.Click(uIRunTestsMenuItem, new Point(118, 16));
        }

        /// <summary>
        /// RecordedMethod15
        /// </summary>
        public void RecordedMethod15()
        {
            //#region Variable Declarations
            //WpfTreeItem uISample_1UnitTestTreeItem = this.UISample_1MicrosoftVisWindow.UITabGroupST003ae79031TabList.UISolutionExplorerTabPage.UISample_1UnitTestTreeItem;
            //WpfMenuItem uIRunTestsMenuItem = this.UIWpfWindow.UIProjectMenu.UIRunTestsMenuItem;
            //#endregion

            //// Right-Click 'Sample_1UnitTest' tree item
            //Mouse.Click(uISample_1UnitTestTreeItem, MouseButtons.Right);

            //// Click 'Run Tests' menu item
            //Mouse.Click(uIRunTestsMenuItem);
        }

        #region Properties
        public virtual RecordedMethod1Params RecordedMethod1Params
        {
            get
            {
                if ((this.mRecordedMethod1Params == null))
                {
                    this.mRecordedMethod1Params = new RecordedMethod1Params();
                }
                return this.mRecordedMethod1Params;
            }
        }

        public virtual RecordedMethod2Params RecordedMethod2Params
        {
            get
            {
                if ((this.mRecordedMethod2Params == null))
                {
                    this.mRecordedMethod2Params = new RecordedMethod2Params();
                }
                return this.mRecordedMethod2Params;
            }
        }

        public virtual RecordedMethod4Params RecordedMethod4Params
        {
            get
            {
                if ((this.mRecordedMethod4Params == null))
                {
                    this.mRecordedMethod4Params = new RecordedMethod4Params();
                }
                return this.mRecordedMethod4Params;
            }
        }

        public virtual RecordedMethod5Params RecordedMethod5Params
        {
            get
            {
                if ((this.mRecordedMethod5Params == null))
                {
                    this.mRecordedMethod5Params = new RecordedMethod5Params();
                }
                return this.mRecordedMethod5Params;
            }
        }

        public UIMicrosoftVisualStudiWindow UIMicrosoftVisualStudiWindow
        {
            get
            {
                if ((this.mUIMicrosoftVisualStudiWindow == null))
                {
                    this.mUIMicrosoftVisualStudiWindow = new UIMicrosoftVisualStudiWindow();
                }
                return this.mUIMicrosoftVisualStudiWindow;
            }
        }

        public UIItemWindow UIItemWindow
        {
            get
            {
                if ((this.mUIItemWindow == null))
                {
                    this.mUIItemWindow = new UIItemWindow();
                }
                return this.mUIItemWindow;
            }
        }

        public UISnipperSnipasteWindow UISnipperSnipasteWindow
        {
            get
            {
                if ((this.mUISnipperSnipasteWindow == null))
                {
                    this.mUISnipperSnipasteWindow = new UISnipperSnipasteWindow();
                }
                return this.mUISnipperSnipasteWindow;
            }
        }

        public UISaveimageasWindow UISaveimageasWindow
        {
            get
            {
                if ((this.mUISaveimageasWindow == null))
                {
                    this.mUISaveimageasWindow = new UISaveimageasWindow();
                }
                return this.mUISaveimageasWindow;
            }
        }

        public UITest1637916794MicrosWindow UITest1637916794MicrosWindow
        {
            get
            {
                if ((this.mUITest1637916794MicrosWindow == null))
                {
                    this.mUITest1637916794MicrosWindow = new UITest1637916794MicrosWindow();
                }
                return this.mUITest1637916794MicrosWindow;
            }
        }

        public UIOptionsWindow UIOptionsWindow
        {
            get
            {
                if ((this.mUIOptionsWindow == null))
                {
                    this.mUIOptionsWindow = new UIOptionsWindow();
                }
                return this.mUIOptionsWindow;
            }
        }

        public UITest1638153053MicrosWindow UITest1638153053MicrosWindow
        {
            get
            {
                if ((this.mUITest1638153053MicrosWindow == null))
                {
                    this.mUITest1638153053MicrosWindow = new UITest1638153053MicrosWindow();
                }
                return this.mUITest1638153053MicrosWindow;
            }
        }

        public UIOpenProjectSolutionWindow UIOpenProjectSolutionWindow
        {
            get
            {
                if ((this.mUIOpenProjectSolutionWindow == null))
                {
                    this.mUIOpenProjectSolutionWindow = new UIOpenProjectSolutionWindow();
                }
                return this.mUIOpenProjectSolutionWindow;
            }
        }

        public UISample_1MicrosoftVisWindow UISample_1MicrosoftVisWindow
        {
            get
            {
                if ((this.mUISample_1MicrosoftVisWindow == null))
                {
                    this.mUISample_1MicrosoftVisWindow = new UISample_1MicrosoftVisWindow();
                }
                return this.mUISample_1MicrosoftVisWindow;
            }
        }

        //public UIWpfWindow UIWpfWindow
        //{
        //    get
        //    {
        //        if ((this.mUIWpfWindow == null))
        //        {
        //            this.mUIWpfWindow = new UIWpfWindow();
        //        }
        //        return this.mUIWpfWindow;
        //    }
        //}

        //public UIProgramManagerWindow UIProgramManagerWindow
        //{
        //    get
        //    {
        //        if ((this.mUIProgramManagerWindow == null))
        //        {
        //            this.mUIProgramManagerWindow = new UIProgramManagerWindow();
        //        }
        //        return this.mUIProgramManagerWindow;
        //    }
        //}
        #endregion

        #region Fields
        private RecordedMethod1Params mRecordedMethod1Params;

        private RecordedMethod2Params mRecordedMethod2Params;

        private RecordedMethod4Params mRecordedMethod4Params;

        private RecordedMethod5Params mRecordedMethod5Params;

        private UIMicrosoftVisualStudiWindow mUIMicrosoftVisualStudiWindow;

        private UIItemWindow mUIItemWindow;

        private UISnipperSnipasteWindow mUISnipperSnipasteWindow;

        private UISaveimageasWindow mUISaveimageasWindow;

        private UITest1637916794MicrosWindow mUITest1637916794MicrosWindow;

        private UIOptionsWindow mUIOptionsWindow;

        private UITest1638153053MicrosWindow mUITest1638153053MicrosWindow;

        private UIOpenProjectSolutionWindow mUIOpenProjectSolutionWindow;

        private UISample_1MicrosoftVisWindow mUISample_1MicrosoftVisWindow;

        private UIWpfWindow mUIWpfWindow;

        //private UIProgramManagerWindow mUIProgramManagerWindow;
        #endregion
    }

    /// <summary>
    /// Parameters to be passed into 'RecordedMethod1'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class RecordedMethod1Params
    {

        #region Fields
        /// <summary>
        /// Type 'scope' in '_Search for templates (Alt+S)' text box
        /// </summary>
        public string UI_SearchfortemplatesAEditText = "scope";

        /// <summary>
        /// Type '{Enter}' in '_Search for templates (Alt+S)' text box
        /// </summary>
        public string UI_SearchfortemplatesAEditSendKeys = "{Enter}";

        /// <summary>
        /// Type 'test' in 'Project name' text box
        /// </summary>
        public string UIProjectnameEditText = "test";

        /// <summary>
        /// Type 'e:\test' in 'Location' text box
        /// </summary>
        public string UILocationEditText = "e:\\test";
        #endregion
    }

    /// <summary>
    /// Parameters to be passed into 'RecordedMethod2'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class RecordedMethod2Params
    {

        #region Fields
        /// <summary>
        /// Type 'scope' in '_Search for templates (Alt+S)' text box
        /// </summary>
        public string UI_SearchfortemplatesAEditText = "scope";

        /// <summary>
        /// Type '{Enter}' in '_Search for templates (Alt+S)' text box
        /// </summary>
        public string UI_SearchfortemplatesAEditSendKeys = "{Enter}";
        #endregion
    }

    /// <summary>
    /// Parameters to be passed into 'RecordedMethod4'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class RecordedMethod4Params
    {

        #region Fields
        /// <summary>
        /// Press keyboard shortcut keys '{LWin}'
        /// </summary>
        public string SendKeys = "{LWin}";
        #endregion
    }

    /// <summary>
    /// Parameters to be passed into 'RecordedMethod5'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class RecordedMethod5Params
    {

        #region Fields
        /// <summary>
        /// Type 'Control + s' in 'Snipper - Snipaste' window
        /// </summary>
        public string UISnipperSnipasteWindow1SendKeys = "s";

        /// <summary>
        /// Select '22.png' in 'File name:' combo box
        /// </summary>
        public string UIFilenameComboBoxEditableItem = "22.png";
        #endregion
    }

    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UIMicrosoftVisualStudiWindow : WpfWindow
    {

        public UIMicrosoftVisualStudiWindow()
        {
            #region Search Criteria
            this.SearchProperties[WpfWindow.PropertyNames.Name] = "Microsoft Visual Studio";
            this.SearchProperties.Add(new PropertyExpression(WpfWindow.PropertyNames.ClassName, "HwndWrapper", PropertyExpressionOperator.Contains));
            this.WindowTitles.Add("Microsoft Visual Studio");
            #endregion
        }

        #region Properties
        public UIUserControl_1Custom UIUserControl_1Custom
        {
            get
            {
                if ((this.mUIUserControl_1Custom == null))
                {
                    this.mUIUserControl_1Custom = new UIUserControl_1Custom(this);
                }
                return this.mUIUserControl_1Custom;
            }
        }

        public UINpdDialogCustom UINpdDialogCustom
        {
            get
            {
                if ((this.mUINpdDialogCustom == null))
                {
                    this.mUINpdDialogCustom = new UINpdDialogCustom(this);
                }
                return this.mUINpdDialogCustom;
            }
        }

        public UIUserControl_1Custom11 UIUserControl_1Custom1
        {
            get
            {
                if ((this.mUIUserControl_1Custom1 == null))
                {
                    this.mUIUserControl_1Custom1 = new UIUserControl_1Custom11(this);
                }
                return this.mUIUserControl_1Custom1;
            }
        }
        #endregion

        #region Fields
        private UIUserControl_1Custom mUIUserControl_1Custom;

        private UINpdDialogCustom mUINpdDialogCustom;

        private UIUserControl_1Custom11 mUIUserControl_1Custom1;
        #endregion
    }

    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UIUserControl_1Custom : WpfCustom
    {

        public UIUserControl_1Custom(UITestControl searchLimitContainer) :
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WpfControl.PropertyNames.ClassName] = "Uia.ProjectCreationView";
            this.SearchProperties[WpfControl.PropertyNames.AutomationId] = "UserControl_1";
            this.WindowTitles.Add("Microsoft Visual Studio");
            #endregion
        }

        #region Properties
        public UISearchControlGroup UISearchControlGroup
        {
            get
            {
                if ((this.mUISearchControlGroup == null))
                {
                    this.mUISearchControlGroup = new UISearchControlGroup(this);
                }
                return this.mUISearchControlGroup;
            }
        }
        #endregion

        #region Fields
        private UISearchControlGroup mUISearchControlGroup;
        #endregion
    }

    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UISearchControlGroup : WpfGroup
    {

        public UISearchControlGroup(UITestControl searchLimitContainer) :
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WpfGroup.PropertyNames.AutomationId] = "SearchControl";
            this.WindowTitles.Add("Microsoft Visual Studio");
            #endregion
        }

        #region Properties
        public WpfEdit UI_SearchfortemplatesAEdit
        {
            get
            {
                if ((this.mUI_SearchfortemplatesAEdit == null))
                {
                    this.mUI_SearchfortemplatesAEdit = new WpfEdit(this);
                    #region Search Criteria
                    this.mUI_SearchfortemplatesAEdit.SearchProperties[WpfEdit.PropertyNames.AutomationId] = "PART_SearchBox";
                    this.mUI_SearchfortemplatesAEdit.WindowTitles.Add("Microsoft Visual Studio");
                    #endregion
                }
                return this.mUI_SearchfortemplatesAEdit;
            }
        }
        #endregion

        #region Fields
        private WpfEdit mUI_SearchfortemplatesAEdit;
        #endregion
    }

    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UINpdDialogCustom : WpfCustom
    {

        public UINpdDialogCustom(UITestControl searchLimitContainer) :
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WpfControl.PropertyNames.ClassName] = "Uia.NewProjectView";
            this.SearchProperties[WpfControl.PropertyNames.AutomationId] = "npdDialog";
            this.WindowTitles.Add("Microsoft Visual Studio");
            #endregion
        }

        #region Properties
        public UIUserControl_1Custom1 UIUserControl_1Custom
        {
            get
            {
                if ((this.mUIUserControl_1Custom == null))
                {
                    this.mUIUserControl_1Custom = new UIUserControl_1Custom1(this);
                }
                return this.mUIUserControl_1Custom;
            }
        }
        #endregion

        #region Fields
        private UIUserControl_1Custom1 mUIUserControl_1Custom;
        #endregion
    }

    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UIUserControl_1Custom1 : WpfCustom
    {

        public UIUserControl_1Custom1(UITestControl searchLimitContainer) :
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WpfControl.PropertyNames.ClassName] = "Uia.ProjectConfigurationView";
            this.SearchProperties[WpfControl.PropertyNames.AutomationId] = "UserControl_1";
            this.WindowTitles.Add("Microsoft Visual Studio");
            #endregion
        }

        #region Properties
        public WpfText UIConfigureyournewprojText
        {
            get
            {
                if ((this.mUIConfigureyournewprojText == null))
                {
                    this.mUIConfigureyournewprojText = new WpfText(this);
                    #region Search Criteria
                    this.mUIConfigureyournewprojText.SearchProperties[WpfText.PropertyNames.AutomationId] = "TitleTextBlock";
                    this.mUIConfigureyournewprojText.WindowTitles.Add("Microsoft Visual Studio");
                    #endregion
                }
                return this.mUIConfigureyournewprojText;
            }
        }

        public UIScrollViewer_1Pane UIScrollViewer_1Pane
        {
            get
            {
                if ((this.mUIScrollViewer_1Pane == null))
                {
                    this.mUIScrollViewer_1Pane = new UIScrollViewer_1Pane(this);
                }
                return this.mUIScrollViewer_1Pane;
            }
        }

        public UILocationCustom UILocationCustom
        {
            get
            {
                if ((this.mUILocationCustom == null))
                {
                    this.mUILocationCustom = new UILocationCustom(this);
                }
                return this.mUILocationCustom;
            }
        }
        #endregion

        #region Fields
        private WpfText mUIConfigureyournewprojText;

        private UIScrollViewer_1Pane mUIScrollViewer_1Pane;

        private UILocationCustom mUILocationCustom;
        #endregion
    }

    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UIScrollViewer_1Pane : WpfPane
    {

        public UIScrollViewer_1Pane(UITestControl searchLimitContainer) :
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WpfPane.PropertyNames.ClassName] = "Uia.ScrollViewer";
            this.SearchProperties[WpfPane.PropertyNames.AutomationId] = "ScrollViewer_1";
            this.WindowTitles.Add("Microsoft Visual Studio");
            #endregion
        }

        #region Properties
        public WpfEdit UIProjectnameEdit
        {
            get
            {
                if ((this.mUIProjectnameEdit == null))
                {
                    this.mUIProjectnameEdit = new WpfEdit(this);
                    #region Search Criteria
                    this.mUIProjectnameEdit.SearchProperties[WpfEdit.PropertyNames.AutomationId] = "projectNameText";
                    this.mUIProjectnameEdit.WindowTitles.Add("Microsoft Visual Studio");
                    #endregion
                }
                return this.mUIProjectnameEdit;
            }
        }
        #endregion

        #region Fields
        private WpfEdit mUIProjectnameEdit;
        #endregion
    }

    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UILocationCustom : WpfCustom
    {

        public UILocationCustom(UITestControl searchLimitContainer) :
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WpfControl.PropertyNames.ClassName] = null;
            this.SearchProperties[WpfControl.PropertyNames.AutomationId] = "locationCmb";
            this.WindowTitles.Add("Microsoft Visual Studio");
            #endregion
        }

        #region Properties
        public WpfEdit UILocationEdit
        {
            get
            {
                if ((this.mUILocationEdit == null))
                {
                    this.mUILocationEdit = new WpfEdit(this);
                    #region Search Criteria
                    this.mUILocationEdit.SearchProperties[WpfEdit.PropertyNames.AutomationId] = "PART_EditableTextBox";
                    this.mUILocationEdit.WindowTitles.Add("Microsoft Visual Studio");
                    #endregion
                }
                return this.mUILocationEdit;
            }
        }
        #endregion

        #region Fields
        private WpfEdit mUILocationEdit;
        #endregion
    }

    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UIUserControl_1Custom11 : WpfCustom
    {

        public UIUserControl_1Custom11(UITestControl searchLimitContainer) :
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WpfControl.PropertyNames.ClassName] = "Uia.GetToCodeWorkflowView";
            this.SearchProperties[WpfControl.PropertyNames.AutomationId] = "UserControl_1";
            this.WindowTitles.Add("Microsoft Visual Studio");
            #endregion
        }

        #region Properties
        public UIScrollViewer_1Pane1 UIScrollViewer_1Pane
        {
            get
            {
                if ((this.mUIScrollViewer_1Pane == null))
                {
                    this.mUIScrollViewer_1Pane = new UIScrollViewer_1Pane1(this);
                }
                return this.mUIScrollViewer_1Pane;
            }
        }
        #endregion

        #region Fields
        private UIScrollViewer_1Pane1 mUIScrollViewer_1Pane;
        #endregion
    }

    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UIScrollViewer_1Pane1 : WpfPane
    {

        public UIScrollViewer_1Pane1(UITestControl searchLimitContainer) :
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WpfPane.PropertyNames.ClassName] = "Uia.ScrollViewer";
            this.SearchProperties[WpfPane.PropertyNames.AutomationId] = "ScrollViewer_1";
            this.WindowTitles.Add("Microsoft Visual Studio");
            #endregion
        }

        #region Properties
        public WpfButton UICreatea_newprojectButton
        {
            get
            {
                if ((this.mUICreatea_newprojectButton == null))
                {
                    this.mUICreatea_newprojectButton = new WpfButton(this);
                    #region Search Criteria
                    this.mUICreatea_newprojectButton.SearchProperties[WpfButton.PropertyNames.AutomationId] = "Button_1";
                    this.mUICreatea_newprojectButton.SearchProperties[WpfButton.PropertyNames.Instance] = "4";
                    this.mUICreatea_newprojectButton.WindowTitles.Add("Microsoft Visual Studio");
                    #endregion
                }
                return this.mUICreatea_newprojectButton;
            }
        }
        #endregion

        #region Fields
        private WpfButton mUICreatea_newprojectButton;
        #endregion
    }

    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UIItemWindow : WinWindow
    {

        public UIItemWindow()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.AccessibleName] = "Desktop 1";
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "#32769";
            #endregion
        }

        #region Properties
        public UIItemWindow1 UIItemWindow1
        {
            get
            {
                if ((this.mUIItemWindow1 == null))
                {
                    this.mUIItemWindow1 = new UIItemWindow1(this);
                }
                return this.mUIItemWindow1;
            }
        }
        #endregion

        #region Fields
        private UIItemWindow1 mUIItemWindow1;
        #endregion
    }

    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UIItemWindow1 : WinWindow
    {

        public UIItemWindow1(UITestControl searchLimitContainer) :
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "VisualStudioGlowWindow";
            this.SearchProperties[WinWindow.PropertyNames.Instance] = "3";
            #endregion
        }

        #region Properties
        public WinClient UIDesktop1Client
        {
            get
            {
                if ((this.mUIDesktop1Client == null))
                {
                    this.mUIDesktop1Client = new WinClient(this);
                }
                return this.mUIDesktop1Client;
            }
        }
        #endregion

        #region Fields
        private WinClient mUIDesktop1Client;
        #endregion
    }

    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UISnipperSnipasteWindow : WinWindow
    {

        public UISnipperSnipasteWindow()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.Name] = "Snipper - Snipaste";
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "Qt5QWindowIcon";
            this.WindowTitles.Add("Snipper - Snipaste");
            #endregion
        }

        #region Properties
        public WinWindow UISnipperSnipasteWindow1
        {
            get
            {
                if ((this.mUISnipperSnipasteWindow1 == null))
                {
                    this.mUISnipperSnipasteWindow1 = new WinWindow(this);
                    #region Search Criteria
                    this.mUISnipperSnipasteWindow1.SearchProperties[WinWindow.PropertyNames.Name] = "Snipper - Snipaste";
                    this.mUISnipperSnipasteWindow1.SearchConfigurations.Add(SearchConfiguration.DisambiguateChild);
                    this.mUISnipperSnipasteWindow1.WindowTitles.Add("Snipper - Snipaste");
                    #endregion
                }
                return this.mUISnipperSnipasteWindow1;
            }
        }
        #endregion

        #region Fields
        private WinWindow mUISnipperSnipasteWindow1;
        #endregion
    }

    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UISaveimageasWindow : WinWindow
    {

        public UISaveimageasWindow()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.Name] = "Save image as";
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "#32770";
            this.WindowTitles.Add("Save image as");
            #endregion
        }

        #region Properties
        public UIDetailsPanePane UIDetailsPanePane
        {
            get
            {
                if ((this.mUIDetailsPanePane == null))
                {
                    this.mUIDetailsPanePane = new UIDetailsPanePane(this);
                }
                return this.mUIDetailsPanePane;
            }
        }

        public UISaveWindow UISaveWindow
        {
            get
            {
                if ((this.mUISaveWindow == null))
                {
                    this.mUISaveWindow = new UISaveWindow(this);
                }
                return this.mUISaveWindow;
            }
        }
        #endregion

        #region Fields
        private UIDetailsPanePane mUIDetailsPanePane;

        private UISaveWindow mUISaveWindow;
        #endregion
    }

    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UIDetailsPanePane : WinPane
    {

        public UIDetailsPanePane(UITestControl searchLimitContainer) :
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinControl.PropertyNames.Name] = "Details Pane";
            this.WindowTitles.Add("Save image as");
            #endregion
        }

        #region Properties
        public WinComboBox UIFilenameComboBox
        {
            get
            {
                if ((this.mUIFilenameComboBox == null))
                {
                    this.mUIFilenameComboBox = new WinComboBox(this);
                    #region Search Criteria
                    this.mUIFilenameComboBox.SearchProperties[WinComboBox.PropertyNames.Name] = "File name:";
                    this.mUIFilenameComboBox.WindowTitles.Add("Save image as");
                    #endregion
                }
                return this.mUIFilenameComboBox;
            }
        }
        #endregion

        #region Fields
        private WinComboBox mUIFilenameComboBox;
        #endregion
    }

    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UISaveWindow : WinWindow
    {

        public UISaveWindow(UITestControl searchLimitContainer) :
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlId] = "1";
            this.WindowTitles.Add("Save image as");
            #endregion
        }

        #region Properties
        public WinButton UISaveButton
        {
            get
            {
                if ((this.mUISaveButton == null))
                {
                    this.mUISaveButton = new WinButton(this);
                    #region Search Criteria
                    this.mUISaveButton.SearchProperties[WinButton.PropertyNames.Name] = "Save";
                    this.mUISaveButton.WindowTitles.Add("Save image as");
                    #endregion
                }
                return this.mUISaveButton;
            }
        }
        #endregion

        #region Fields
        private WinButton mUISaveButton;
        #endregion
    }

    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UITest1637916794MicrosWindow : WpfWindow
    {

        public UITest1637916794MicrosWindow()
        {
            #region Search Criteria
            this.SearchProperties[WpfWindow.PropertyNames.Name] = "test1637916794 - Microsoft Visual Studio";
            this.SearchProperties.Add(new PropertyExpression(WpfWindow.PropertyNames.ClassName, "HwndWrapper", PropertyExpressionOperator.Contains));
            this.WindowTitles.Add("test1637916794 - Microsoft Visual Studio");
            #endregion
        }

        #region Properties
        public UIUserControl_1Custom2 UIUserControl_1Custom
        {
            get
            {
                if ((this.mUIUserControl_1Custom == null))
                {
                    this.mUIUserControl_1Custom = new UIUserControl_1Custom2(this);
                }
                return this.mUIUserControl_1Custom;
            }
        }
        #endregion

        #region Fields
        private UIUserControl_1Custom2 mUIUserControl_1Custom;
        #endregion
    }

    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UIUserControl_1Custom2 : WpfCustom
    {

        public UIUserControl_1Custom2(UITestControl searchLimitContainer) :
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WpfControl.PropertyNames.ClassName] = "Uia.ComparableTabControl";
            this.SearchProperties[WpfControl.PropertyNames.AutomationId] = "UserControl_1";
            this.WindowTitles.Add("test1637916794 - Microsoft Visual Studio");
            #endregion
        }

        #region Properties
        public UILeftTabControlTabList UILeftTabControlTabList
        {
            get
            {
                if ((this.mUILeftTabControlTabList == null))
                {
                    this.mUILeftTabControlTabList = new UILeftTabControlTabList(this);
                }
                return this.mUILeftTabControlTabList;
            }
        }
        #endregion

        #region Fields
        private UILeftTabControlTabList mUILeftTabControlTabList;
        #endregion
    }

    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UILeftTabControlTabList : WpfTabList
    {

        public UILeftTabControlTabList(UITestControl searchLimitContainer) :
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WpfTabList.PropertyNames.AutomationId] = "LeftTabControl";
            this.WindowTitles.Add("test1637916794 - Microsoft Visual Studio");
            #endregion
        }

        #region Properties
        public UISystemWindowsControlTabPage UISystemWindowsControlTabPage
        {
            get
            {
                if ((this.mUISystemWindowsControlTabPage == null))
                {
                    this.mUISystemWindowsControlTabPage = new UISystemWindowsControlTabPage(this);
                }
                return this.mUISystemWindowsControlTabPage;
            }
        }
        #endregion

        #region Fields
        private UISystemWindowsControlTabPage mUISystemWindowsControlTabPage;
        #endregion
    }

    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UISystemWindowsControlTabPage : WpfTabPage
    {

        public UISystemWindowsControlTabPage(UITestControl searchLimitContainer) :
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WpfTabPage.PropertyNames.Name] = "System.Windows.Controls.TabItem Header: Content:";
            this.WindowTitles.Add("test1637916794 - Microsoft Visual Studio");
            #endregion
        }

        #region Properties
        public WpfButton UIM0595948483737262615Button
        {
            get
            {
                if ((this.mUIM0595948483737262615Button == null))
                {
                    this.mUIM0595948483737262615Button = new WpfButton(this);
                    #region Search Criteria
                    this.mUIM0595948483737262615Button.SearchProperties[WpfButton.PropertyNames.AutomationId] = "UpButton";
                    this.mUIM0595948483737262615Button.WindowTitles.Add("test1637916794 - Microsoft Visual Studio");
                    #endregion
                }
                return this.mUIM0595948483737262615Button;
            }
        }
        #endregion

        #region Fields
        private WpfButton mUIM0595948483737262615Button;
        #endregion
    }

    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UIOptionsWindow : WinWindow
    {

        public UIOptionsWindow()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.Name] = "Options";
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "#32770";
            this.WindowTitles.Add("Options");
            #endregion
        }

        #region Properties
        public UIOptionsTitleBar UIOptionsTitleBar
        {
            get
            {
                if ((this.mUIOptionsTitleBar == null))
                {
                    this.mUIOptionsTitleBar = new UIOptionsTitleBar(this);
                }
                return this.mUIOptionsTitleBar;
            }
        }

        public UIItemWindow2 UIItemWindow
        {
            get
            {
                if ((this.mUIItemWindow == null))
                {
                    this.mUIItemWindow = new UIItemWindow2(this);
                }
                return this.mUIItemWindow;
            }
        }
        #endregion

        #region Fields
        private UIOptionsTitleBar mUIOptionsTitleBar;

        private UIItemWindow2 mUIItemWindow;
        #endregion
    }

    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UIOptionsTitleBar : WinTitleBar
    {

        public UIOptionsTitleBar(UITestControl searchLimitContainer) :
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.WindowTitles.Add("Options");
            #endregion
        }

        #region Properties
        public WinButton UIContexthelpButton
        {
            get
            {
                if ((this.mUIContexthelpButton == null))
                {
                    this.mUIContexthelpButton = new WinButton(this);
                    #region Search Criteria
                    this.mUIContexthelpButton.SearchProperties[WinButton.PropertyNames.Name] = "Context help";
                    this.mUIContexthelpButton.WindowTitles.Add("Options");
                    #endregion
                }
                return this.mUIContexthelpButton;
            }
        }
        #endregion

        #region Fields
        private WinButton mUIContexthelpButton;
        #endregion
    }

    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UIItemWindow2 : WinWindow
    {

        public UIItemWindow2(UITestControl searchLimitContainer) :
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties.Add(new PropertyExpression(WinWindow.PropertyNames.ClassName, "WindowsForms10.Window", PropertyExpressionOperator.Contains));
            this.WindowTitles.Add("Options");
            #endregion
        }

        #region Properties
        public UIItemClient UIItemClient
        {
            get
            {
                if ((this.mUIItemClient == null))
                {
                    this.mUIItemClient = new UIItemClient(this);
                }
                return this.mUIItemClient;
            }
        }
        #endregion

        #region Fields
        private UIItemClient mUIItemClient;
        #endregion
    }

    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UIItemClient : WinClient
    {

        public UIItemClient(UITestControl searchLimitContainer) :
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.WindowTitles.Add("Options");
            #endregion
        }

        #region Properties
        public UIItemPane UIItemPane
        {
            get
            {
                if ((this.mUIItemPane == null))
                {
                    this.mUIItemPane = new UIItemPane(this);
                }
                return this.mUIItemPane;
            }
        }
        #endregion

        #region Fields
        private UIItemPane mUIItemPane;
        #endregion
    }

    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UIItemPane : WpfPane
    {

        public UIItemPane(UITestControl searchLimitContainer) :
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.WindowTitles.Add("Options");
            #endregion
        }

        #region Properties
        public UIItemCustom UIItemCustom
        {
            get
            {
                if ((this.mUIItemCustom == null))
                {
                    this.mUIItemCustom = new UIItemCustom(this);
                }
                return this.mUIItemCustom;
            }
        }
        #endregion

        #region Fields
        private UIItemCustom mUIItemCustom;
        #endregion
    }

    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UIItemCustom : WpfCustom
    {

        public UIItemCustom(UITestControl searchLimitContainer) :
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WpfControl.PropertyNames.ClassName] = "Uia.ScopeGeneralSettingsUserControl";
            this.WindowTitles.Add("Options");
            #endregion
        }

        #region Properties
        public UIScrollViewer_1Pane2 UIScrollViewer_1Pane
        {
            get
            {
                if ((this.mUIScrollViewer_1Pane == null))
                {
                    this.mUIScrollViewer_1Pane = new UIScrollViewer_1Pane2(this);
                }
                return this.mUIScrollViewer_1Pane;
            }
        }
        #endregion

        #region Fields
        private UIScrollViewer_1Pane2 mUIScrollViewer_1Pane;
        #endregion
    }

    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UIScrollViewer_1Pane2 : WpfPane
    {

        public UIScrollViewer_1Pane2(UITestControl searchLimitContainer) :
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WpfPane.PropertyNames.ClassName] = "Uia.ScrollViewer";
            this.SearchProperties[WpfPane.PropertyNames.AutomationId] = "ScrollViewer_1";
            this.WindowTitles.Add("Options");
            #endregion
        }

        #region Properties
        public WpfText UILocalMetadataRootText
        {
            get
            {
                if ((this.mUILocalMetadataRootText == null))
                {
                    this.mUILocalMetadataRootText = new WpfText(this);
                    #region Search Criteria
                    this.mUILocalMetadataRootText.SearchProperties[WpfText.PropertyNames.Name] = "Local Metadata Root";
                    this.mUILocalMetadataRootText.WindowTitles.Add("Options");
                    #endregion
                }
                return this.mUILocalMetadataRootText;
            }
        }
        #endregion

        #region Fields
        private WpfText mUILocalMetadataRootText;
        #endregion
    }

    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UITest1638153053MicrosWindow : WpfWindow
    {

        public UITest1638153053MicrosWindow()
        {
            #region Search Criteria
            this.SearchProperties[WpfWindow.PropertyNames.Name] = "test1638153053 - Microsoft Visual Studio";
            this.SearchProperties.Add(new PropertyExpression(WpfWindow.PropertyNames.ClassName, "HwndWrapper", PropertyExpressionOperator.Contains));
            this.WindowTitles.Add("test1638153053 - Microsoft Visual Studio");
            #endregion
        }

        #region Properties
        public UIWpfTextViewHostCustom UIWpfTextViewHostCustom
        {
            get
            {
                if ((this.mUIWpfTextViewHostCustom == null))
                {
                    this.mUIWpfTextViewHostCustom = new UIWpfTextViewHostCustom(this);
                }
                return this.mUIWpfTextViewHostCustom;
            }
        }

        public UITabGroupST003ae79031TabList UITabGroupST003ae79031TabList
        {
            get
            {
                if ((this.mUITabGroupST003ae79031TabList == null))
                {
                    this.mUITabGroupST003ae79031TabList = new UITabGroupST003ae79031TabList(this);
                }
                return this.mUITabGroupST003ae79031TabList;
            }
        }
        #endregion

        #region Fields
        private UIWpfTextViewHostCustom mUIWpfTextViewHostCustom;

        private UITabGroupST003ae79031TabList mUITabGroupST003ae79031TabList;
        #endregion
    }

    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UIWpfTextViewHostCustom : WpfCustom
    {

        public UIWpfTextViewHostCustom(UITestControl searchLimitContainer) :
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WpfControl.PropertyNames.ClassName] = null;
            this.SearchProperties[WpfControl.PropertyNames.AutomationId] = "WpfTextViewHost";
            this.WindowTitles.Add("test1638153053 - Microsoft Visual Studio");
            #endregion
        }

        #region Properties
        public UIUserControl_1Custom3 UIUserControl_1Custom
        {
            get
            {
                if ((this.mUIUserControl_1Custom == null))
                {
                    this.mUIUserControl_1Custom = new UIUserControl_1Custom3(this);
                }
                return this.mUIUserControl_1Custom;
            }
        }
        #endregion

        #region Fields
        private UIUserControl_1Custom3 mUIUserControl_1Custom;
        #endregion
    }

    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UIUserControl_1Custom3 : WpfCustom
    {

        public UIUserControl_1Custom3(UITestControl searchLimitContainer) :
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WpfControl.PropertyNames.ClassName] = "Uia.ComparableTabControl";
            this.SearchProperties[WpfControl.PropertyNames.AutomationId] = "UserControl_1";
            this.WindowTitles.Add("test1638153053 - Microsoft Visual Studio");
            #endregion
        }

        #region Properties
        public UIAnalyticresourceText UIAnalyticresourceText
        {
            get
            {
                if ((this.mUIAnalyticresourceText == null))
                {
                    this.mUIAnalyticresourceText = new UIAnalyticresourceText(this);
                }
                return this.mUIAnalyticresourceText;
            }
        }
        #endregion

        #region Fields
        private UIAnalyticresourceText mUIAnalyticresourceText;
        #endregion
    }

    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UIAnalyticresourceText : WpfText
    {

        public UIAnalyticresourceText(UITestControl searchLimitContainer) :
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WpfText.PropertyNames.Name] = "Analytic resource:";
            this.WindowTitles.Add("test1638153053 - Microsoft Visual Studio");
            #endregion
        }

        #region Properties
        public WpfComboBox UIItemComboBox
        {
            get
            {
                if ((this.mUIItemComboBox == null))
                {
                    this.mUIItemComboBox = new WpfComboBox(this);
                    #region Search Criteria
                    this.mUIItemComboBox.SearchConfigurations.Add(SearchConfiguration.NextSibling);
                    this.mUIItemComboBox.WindowTitles.Add("test1638153053 - Microsoft Visual Studio");
                    #endregion
                }
                return this.mUIItemComboBox;
            }
        }
        #endregion

        #region Fields
        private WpfComboBox mUIItemComboBox;
        #endregion
    }

    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UITabGroupST003ae79031TabList : WpfTabList
    {

        public UITabGroupST003ae79031TabList(UITestControl searchLimitContainer) :
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WpfTabList.PropertyNames.AutomationId] = "TabGroup|ST:0:0:{3ae79031-e1bc-11d0-8f78-00a0c9110057}|ST:0:0:{1c64b9c2-e352-428e" +
                "-a56d-0ace190b99a6}";
            this.WindowTitles.Add("test1638153053 - Microsoft Visual Studio");
            #endregion
        }

        #region Properties
        public UISearchControlGroup1 UISearchControlGroup
        {
            get
            {
                if ((this.mUISearchControlGroup == null))
                {
                    this.mUISearchControlGroup = new UISearchControlGroup1(this);
                }
                return this.mUISearchControlGroup;
            }
        }
        #endregion

        #region Fields
        private UISearchControlGroup1 mUISearchControlGroup;
        #endregion
    }

    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UISearchControlGroup1 : WpfGroup
    {

        public UISearchControlGroup1(UITestControl searchLimitContainer) :
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WpfGroup.PropertyNames.AutomationId] = "SearchControl";
            this.WindowTitles.Add("test1638153053 - Microsoft Visual Studio");
            #endregion
        }

        #region Properties
        public WpfEdit UISearchSolutionExplorEdit
        {
            get
            {
                if ((this.mUISearchSolutionExplorEdit == null))
                {
                    this.mUISearchSolutionExplorEdit = new WpfEdit(this);
                    #region Search Criteria
                    this.mUISearchSolutionExplorEdit.SearchProperties[WpfEdit.PropertyNames.AutomationId] = "PART_SearchBox";
                    this.mUISearchSolutionExplorEdit.WindowTitles.Add("test1638153053 - Microsoft Visual Studio");
                    #endregion
                }
                return this.mUISearchSolutionExplorEdit;
            }
        }
        #endregion

        #region Fields
        private WpfEdit mUISearchSolutionExplorEdit;
        #endregion
    }

    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UIOpenProjectSolutionWindow : WinWindow
    {

        public UIOpenProjectSolutionWindow()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.Name] = "Open Project/Solution";
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "#32770";
            this.WindowTitles.Add("Open Project/Solution");
            #endregion
        }

        #region Properties
        public UICommandModuleToolBar UICommandModuleToolBar
        {
            get
            {
                if ((this.mUICommandModuleToolBar == null))
                {
                    this.mUICommandModuleToolBar = new UICommandModuleToolBar(this);
                }
                return this.mUICommandModuleToolBar;
            }
        }

        public UIItemWindow3 UIItemWindow
        {
            get
            {
                if ((this.mUIItemWindow == null))
                {
                    this.mUIItemWindow = new UIItemWindow3(this);
                }
                return this.mUIItemWindow;
            }
        }
        #endregion

        #region Fields
        private UICommandModuleToolBar mUICommandModuleToolBar;

        private UIItemWindow3 mUIItemWindow;
        #endregion
    }

    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UICommandModuleToolBar : WinToolBar
    {

        public UICommandModuleToolBar(UITestControl searchLimitContainer) :
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinToolBar.PropertyNames.Name] = "Command Module";
            this.WindowTitles.Add("Open Project/Solution");
            #endregion
        }

        #region Properties
        public WinCheckBox UIPreviewpaneCheckBox
        {
            get
            {
                if ((this.mUIPreviewpaneCheckBox == null))
                {
                    this.mUIPreviewpaneCheckBox = new WinCheckBox(this);
                    #region Search Criteria
                    this.mUIPreviewpaneCheckBox.SearchProperties[WinCheckBox.PropertyNames.Name] = "Preview pane";
                    this.mUIPreviewpaneCheckBox.WindowTitles.Add("Open Project/Solution");
                    #endregion
                }
                return this.mUIPreviewpaneCheckBox;
            }
        }

        public WinSplitButton UIViewsSplitButton
        {
            get
            {
                if ((this.mUIViewsSplitButton == null))
                {
                    this.mUIViewsSplitButton = new WinSplitButton(this);
                    #region Search Criteria
                    this.mUIViewsSplitButton.SearchProperties[WinButton.PropertyNames.Name] = "Views";
                    this.mUIViewsSplitButton.WindowTitles.Add("Open Project/Solution");
                    #endregion
                }
                return this.mUIViewsSplitButton;
            }
        }
        #endregion

        #region Fields
        private WinCheckBox mUIPreviewpaneCheckBox;

        private WinSplitButton mUIViewsSplitButton;
        #endregion
    }

    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UIItemWindow3 : WinWindow
    {

        public UIItemWindow3(UITestControl searchLimitContainer) :
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "UniversalSearchBand";
            this.WindowTitles.Add("Open Project/Solution");
            #endregion
        }

        #region Properties
        public UIOpenProjectSolutionClient UIOpenProjectSolutionClient
        {
            get
            {
                if ((this.mUIOpenProjectSolutionClient == null))
                {
                    this.mUIOpenProjectSolutionClient = new UIOpenProjectSolutionClient(this);
                }
                return this.mUIOpenProjectSolutionClient;
            }
        }
        #endregion

        #region Fields
        private UIOpenProjectSolutionClient mUIOpenProjectSolutionClient;
        #endregion
    }

    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UIOpenProjectSolutionClient : WinClient
    {

        public UIOpenProjectSolutionClient(UITestControl searchLimitContainer) :
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.WindowTitles.Add("Open Project/Solution");
            #endregion
        }

        #region Properties
        public WinWindow UISearchEditBoxWindow
        {
            get
            {
                if ((this.mUISearchEditBoxWindow == null))
                {
                    this.mUISearchEditBoxWindow = new WinWindow(this);
                    #region Search Criteria
                    this.mUISearchEditBoxWindow.SearchProperties[WinWindow.PropertyNames.Name] = "SearchEditBox";
                    this.mUISearchEditBoxWindow.SearchProperties[WinWindow.PropertyNames.ClassName] = "ModernSearchBox";
                    this.mUISearchEditBoxWindow.WindowTitles.Add("Open Project/Solution");
                    #endregion
                }
                return this.mUISearchEditBoxWindow;
            }
        }

        public WinEdit UISearchEditBoxEdit
        {
            get
            {
                if ((this.mUISearchEditBoxEdit == null))
                {
                    this.mUISearchEditBoxEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUISearchEditBoxEdit.SearchProperties[WinEdit.PropertyNames.Name] = "SearchEditBox";
                    this.mUISearchEditBoxEdit.WindowTitles.Add("Open Project/Solution");
                    #endregion
                }
                return this.mUISearchEditBoxEdit;
            }
        }
        #endregion

        #region Fields
        private WinWindow mUISearchEditBoxWindow;

        private WinEdit mUISearchEditBoxEdit;
        #endregion
    }

    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UISample_1MicrosoftVisWindow : WpfWindow
    {

        public UISample_1MicrosoftVisWindow()
        {
            #region Search Criteria
            this.SearchProperties[WpfWindow.PropertyNames.Name] = "Sample_1 - Microsoft Visual Studio";
            this.SearchProperties.Add(new PropertyExpression(WpfWindow.PropertyNames.ClassName, "HwndWrapper", PropertyExpressionOperator.Contains));
            this.WindowTitles.Add("Sample_1 - Microsoft Visual Studio");
            #endregion
        }

        #region Properties
        public UITabGroupST003ae79031TabList1 UITabGroupST003ae79031TabList
        {
            get
            {
                if ((this.mUITabGroupST003ae79031TabList == null))
                {
                    this.mUITabGroupST003ae79031TabList = new UITabGroupST003ae79031TabList1(this);
                }
                return this.mUITabGroupST003ae79031TabList;
            }
        }
        #endregion

        #region Fields
        private UITabGroupST003ae79031TabList1 mUITabGroupST003ae79031TabList;
        #endregion
    }

    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UITabGroupST003ae79031TabList1 : WpfTabList
    {

        public UITabGroupST003ae79031TabList1(UITestControl searchLimitContainer) :
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WpfTabList.PropertyNames.AutomationId] = "TabGroup|ST:0:0:{3ae79031-e1bc-11d0-8f78-00a0c9110057}|ST:0:0:{1c64b9c2-e352-428e" +
                "-a56d-0ace190b99a6}|ST:0:0:{c9c0ae26-aa77-11d2-b3f0-0000f87570ee}";
            this.WindowTitles.Add("Sample_1 - Microsoft Visual Studio");
            #endregion
        }

        #region Properties
        public UISolutionExplorerTabPage UISolutionExplorerTabPage
        {
            get
            {
                if ((this.mUISolutionExplorerTabPage == null))
                {
                    this.mUISolutionExplorerTabPage = new UISolutionExplorerTabPage(this);
                }
                return this.mUISolutionExplorerTabPage;
            }
        }
        #endregion

        #region Fields
        private UISolutionExplorerTabPage mUISolutionExplorerTabPage;
        #endregion
    }

    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UISolutionExplorerTabPage : WpfTabPage
    {

        public UISolutionExplorerTabPage(UITestControl searchLimitContainer) :
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WpfTabPage.PropertyNames.AutomationId] = "TAB_ST:0:0:{3ae79031-e1bc-11d0-8f78-00a0c9110057}";
            this.WindowTitles.Add("Sample_1 - Microsoft Visual Studio");
            #endregion
        }

        #region Properties
        public WpfTreeItem UIScopescriptTreeItem
        {
            get
            {
                if ((this.mUIScopescriptTreeItem == null))
                {
                    this.mUIScopescriptTreeItem = new WpfTreeItem(this);
                    #region Search Criteria
                    this.mUIScopescriptTreeItem.SearchProperties[WpfTreeItem.PropertyNames.Name] = "Scope.script";
                    this.mUIScopescriptTreeItem.WindowTitles.Add("Sample_1 - Microsoft Visual Studio");
                    #endregion
                }
                return this.mUIScopescriptTreeItem;
            }
        }

        public WpfTreeItem UISample_1UnitTestTreeItem
        {
            get
            {
                if ((this.mUISample_1UnitTestTreeItem == null))
                {
                    this.mUISample_1UnitTestTreeItem = new WpfTreeItem(this);
                    #region Search Criteria
                    this.mUISample_1UnitTestTreeItem.SearchProperties[WpfTreeItem.PropertyNames.Name] = "Sample_1UnitTest";
                    this.mUISample_1UnitTestTreeItem.WindowTitles.Add("Sample_1 - Microsoft Visual Studio");
                    #endregion
                }
                return this.mUISample_1UnitTestTreeItem;
            }
        }
        #endregion

        #region Fields
        private WpfTreeItem mUIScopescriptTreeItem;

        private WpfTreeItem mUISample_1UnitTestTreeItem;
        #endregion
    }

    //[GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    //public class UIWpfWindow : WpfWindow
    //{

    //    public UIWpfWindow()
    //    {
    //        #region Search Criteria
    //        this.SearchProperties.Add(new PropertyExpression(WpfWindow.PropertyNames.ClassName, "HwndWrapper", PropertyExpressionOperator.Contains));
    //        #endregion
    //    }

    //    #region Properties
        //public UIItemMenu UIItemMenu
        //{
        //    get
        //    {
        //        if ((this.mUIItemMenu == null))
        //        {
        //            this.mUIItemMenu = new UIItemMenu(this);
        //        }
        //        return this.mUIItemMenu;
        //    }
        //}

        //public UIProjectMenu UIProjectMenu
        //{
        //    get
        //    {
        //        if ((this.mUIProjectMenu == null))
        //        {
        //            this.mUIProjectMenu = new UIProjectMenu(this);
        //        }
        //        return this.mUIProjectMenu;
        //    }
        //}
        //#endregion

        //#region Fields
        //private UIItemMenu mUIItemMenu;

        //private UIProjectMenu mUIProjectMenu;
        //#endregion
    }

    //[GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    //public class UIItemMenu : WpfMenu
    //{

    //    public UIItemMenu(UITestControl searchLimitContainer) :
    //            base(searchLimitContainer)
    //    {
    //        #region Search Criteria
    //        this.SearchProperties[WpfMenu.PropertyNames.ClassName] = "Uia.ContextMenu";
    //        this.SearchProperties[WpfMenu.PropertyNames.Name] = "Item";
    //        #endregion
    //    }

        //#region Properties
        //public WpfMenuItem UIBuildScriptMenuItem
        //{
        //    get
        //    {
        //        if ((this.mUIBuildScriptMenuItem == null))
        //        {
        //            this.mUIBuildScriptMenuItem = new WpfMenuItem(this);
        //            #region Search Criteria
        //            this.mUIBuildScriptMenuItem.SearchProperties[WpfMenuItem.PropertyNames.Name] = "Build Script";
        //            #endregion
        //        }
        //        return this.mUIBuildScriptMenuItem;
        //    }
        //}

        //public WpfMenuItem UIDebugLocallyMenuItem
        //{
        //    get
        //    {
        //        if ((this.mUIDebugLocallyMenuItem == null))
        //        {
        //            this.mUIDebugLocallyMenuItem = new WpfMenuItem(this);
        //            #region Search Criteria
        //            this.mUIDebugLocallyMenuItem.SearchProperties[WpfMenuItem.PropertyNames.Name] = "Debug Locally";
        //            #endregion
        //        }
        //        return this.mUIDebugLocallyMenuItem;
        //    }
        //}
        //#endregion

    //    #region Fields
    //    private WpfMenuItem mUIBuildScriptMenuItem;

    //    private WpfMenuItem mUIDebugLocallyMenuItem;
    //    #endregion
    //}

    //[GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    //public class UIProjectMenu : WpfMenu
    //{

    //    public UIProjectMenu(UITestControl searchLimitContainer) :
    //            base(searchLimitContainer)
    //    {
    //        #region Search Criteria
    //        this.SearchProperties[WpfMenu.PropertyNames.ClassName] = "Uia.ContextMenu";
    //        this.SearchProperties[WpfMenu.PropertyNames.Name] = "Project";
    //        #endregion
    //    }

        //#region Properties
        //public WpfMenuItem UIRunTestsMenuItem
        //{
        //    get
        //    {
        //        if ((this.mUIRunTestsMenuItem == null))
        //        {
        //            this.mUIRunTestsMenuItem = new WpfMenuItem(this);
        //            #region Search Criteria
        //            this.mUIRunTestsMenuItem.SearchProperties[WpfMenuItem.PropertyNames.Name] = "Run Tests";
        //            #endregion
        //        }
        //        return this.mUIRunTestsMenuItem;
        //    }
        //}
        //#endregion

    //    #region Fields
    //    private WpfMenuItem mUIRunTestsMenuItem;
    //    #endregion
    //}

    //[GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    //public class UIProgramManagerWindow : WinWindow
    //{

    //    public UIProgramManagerWindow()
    //    {
    //        #region Search Criteria
    //        this.SearchProperties[WinWindow.PropertyNames.Name] = "Program Manager";
    //        this.SearchProperties[WinWindow.PropertyNames.ClassName] = "Progman";
    //        this.WindowTitles.Add("Program Manager");
    //        #endregion
    //    }

    //    #region Properties
    //    public UIFolderViewWindow UIFolderViewWindow
    //    {
    //        get
    //        {
    //            if ((this.mUIFolderViewWindow == null))
    //            {
    //                this.mUIFolderViewWindow = new UIFolderViewWindow(this);
    //            }
    //            return this.mUIFolderViewWindow;
    //        }
    //    }
    //    #endregion

    //    #region Fields
    //    private UIFolderViewWindow mUIFolderViewWindow;
    //    #endregion
    //}

    //[GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    //public class UIFolderViewWindow : WinWindow
    //{

    //    public UIFolderViewWindow(UITestControl searchLimitContainer) :
    //            base(searchLimitContainer)
    //    {
    //        #region Search Criteria
    //        this.SearchProperties[WinWindow.PropertyNames.ControlId] = "1";
    //        this.WindowTitles.Add("Program Manager");
    //        #endregion
    //    }

    //    #region Properties
    //    public WinList UIDesktopList
    //    {
    //        get
    //        {
    //            if ((this.mUIDesktopList == null))
    //            {
    //                this.mUIDesktopList = new WinList(this);
    //                #region Search Criteria
    //                this.mUIDesktopList.SearchProperties[WinList.PropertyNames.Name] = "Desktop";
    //                this.mUIDesktopList.WindowTitles.Add("Program Manager");
    //                #endregion
    //            }
    //            return this.mUIDesktopList;
    //        }
    //    }
    //    #endregion

    //    #region Fields
    //    private WinList mUIDesktopList;
    //    #endregion
    

